// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypxtbnerkjhtjzdglixm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweHRibmVya2podGp6ZGdsaXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzOTMxOTQsImV4cCI6MjA4NTk2OTE5NH0.iokbcdDN7XTaTTqkvY3dtNwwhR1OadwBafffmc3Grpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});